### ISSUE TITLE
TS Web Requests -Incorrect Duration for requests

### ISSUE THREAD

**Issue by rk2511** [tableau/community-tableau-server-insights#56]
I saw that the calculation used for the duration is FLOAT(DATEDIFF('second',created at, completed at)).
Even then this is rounding off the value to integers.
Also, more importantly, for some type of requests the duration is getting rounded off to zero.

This can be replicated and found out by
Create a calculated filed - (Completed at - Created at)*86400
Compare the results

**Comment by mcoles** [comment]
Rounding to the nearest whole second was the original intention, primarily because getting more precision didn't seem to matter much in terms of viz load performance analysis, and it would have required more complex calcs. But I think you're right that it's important to do, so I'll edit it to include millisecond precision.

**Comment by rk2511** [comment]
Hi mcoles,
Thanks for the response. I highlighted the problem  not for the precision but because the difference between the actual and expected was huge. For example, When using (Completed at - Created at)*86400 lets say we get a value 10 but with FLOAT(DATEDIFF('second',created at, completed at)) the value would be like say 15.
