### ISSUE TITLE
Job duration displays negative value in TS Background Tasks

### ISSUE THREAD

**Issue by sapna-nyk** [tableau/community-tableau-server-insights#68]
We have build a report showing extracts taking longer duration to refresh versus their usage. We are currently doing a full refresh of the TS Background Tasks on a daily basis. We are seeing couple of entries where the extracts refresh job is showing negative value against the job duration column. I assume its because the start time gets logged and the end time is not getting captured. I tried doing an additional extract refresh run for the TS Background Tasks which solved the negative values for other entries however it still shows negative value for the TS Background Tasks refresh job itself.

This is against v2.02 of TS Content, and v2021.4 of Tableau Server.

This is how we are calculating the job Duration (seconds)
DATEDIFF('second', [Started At], IFNULL([Completed At], [Current Datetime])).

**Comment by mcoles** [comment]
Believe this is due to the NOW() function in PostgreSQL in my custom SQL converting to local time when you extract the data in Tableau. Fix will be to ensure the [Current Datetime] field always reflects UTC, since both [Started At] and [Completed At] always reflect UTC times. Updating the custom SQL like so seems to fix it:

`    CURRENT_TIMESTAMP AT TIME ZONE 'UTC'                AS "Current Datetime" ,`

**Comment by sapna-nyk** [comment]
This worked. Thank you so much Matt!
Are you planning to incorporate this change in future releases of the data source or should we make a note of it to make changes at our end?

**Comment by mcoles** [comment]
I'd make a note on your end--it will be incorporated, but no ETA on the
next release.

**Comment by mcoles** [comment]
This is resolved with the 04.01 release.
