### ISSUE TITLE
Cannot connect these from Desktop to server Version: 2022.1.6 (64-bit Linux)

### ISSUE THREAD

**Issue by amarkoe2018** [tableau/community-tableau-server-insights#72]
Using the 03.01 versions of the twb files.

We have Tableau Server Version: 2022.1.6 (20221.22.0902.1602) 64-bit Linux.
I'm using macOS Monterey Version 12.6 with Tableau Desktop Version 2022.1.4 (20221.22.0712.0324) 64-bit.

I try to connect to the server with...
**Server name** XXXXXX
**Port** 8060
**Database** workgroup
**Authentication** Username and Password
**Username** readonly
**Password** XXXX
and tried both **Require SSL** and **not**

The Error Message is : 

> An error occurred while communicating with PostgreSQL
> Unable to connect to the server. Check that the server is running and that you have access privileges to the requested database.
> Error Code: BC42EF73
> The connection attempt failed.
> Unable to connect to the PostgreSQL server "XXXXXX". Check that the server is running and that you have access privileges to the requested database.

The Postgres Driver is a JDBC jar file, and seems to be working, because I can connect to the repo via Terminal and Postico.

The /etc/odbcinst.ini file looks like this, because we use Redshift.

```
[ODBC Drivers]
Amazon Redshift (x64)=Installed

[Amazon Redshift (x64)]
Description=Amazon Redshift ODBC Driver(64-bit)
Driver=/opt/amazon/redshiftodbc/lib/64/libamazonredshiftodbc64.so
```

I'm wondering if the existence of this ODBC Driver for Redshift is somehow blocking the ability for Tableau Desktop to reach the Repo?

**Comment by amarkoe2018** [comment]
I was able to import one of the files directly to the server from the web UI. On there I was able to get it connected. I don't know yet, if I will be able to download it now, and connect via my desktop software. I will try when I get a chance.

**Comment by amarkoe2018** [comment]
It still doesn't work. I downloaded the version that was successfully connected on the Server, but it still won't let me connect from Tableau Desktop. 
I have the parameters filled in, so it isn't related to those.

**Comment by mcoles** [comment]
So the issue, if I understand correctly, is that you can't connet to the Tableau Server repository database from Tableau Desktop on your Mac, but you can from Tableau Server if you publish the TDS up directly, and you can via third-party tools from your Mac as well? Everything works everywhere except when you use Tableau Desktop from your Mac?

I wouldn't think that's a driver issue, because you're not getting an error about drivers. It's trying to connect, but can't. Typically I would suggest making sure you've [opened up access](https://help.tableau.com/current/server/en-us/perf_collect_server_repo.htm), because that's the error I would expect if you hadn't. Or there's a firewall rule somewhere preventing you from connecting. But again, if you're able to connect to the repo via other PostgreSQL clients also running directly on your Mac, it kinda blows that idea up.

I'm not a Mac person so I'm not familiar with how to configure drivers on that OS, but Googling around, some other things I might suggest are:

- Try making sure you're [using the fully qualified name for the server](https://help.tableau.com/current/pro/desktop/en-us/examples_postgresql.htm#sign-in-on-a-mac), rather than the short name
- Try uninstalling / reinstalling Desktop - it should install the JDBC driver for PostgreSQL automatically, maybe this will correct any driver issues?
- Check any firewall rules you might have on your local machine that might prevent Tableau Desktop from communicating with your repo
- Try verifiying that you can connect to _another_ PostgreSQL database, if you happen to have one. Maybe a test Tableau Server's repo, or stand up a test PostgreSQL instance on your own.
- See if someone else (who's authorized to do so) can connect to the Tableau Serve repo via their Desktop instance


Hope that helps. Maybe someone else can chime in on this who's encountered this kind of thing before.
